.docker: &docker
  image: docker:stable
  services:
    - docker:dind

.dev-only: &dev-only
  only:
  - develop
  - /^feature.*$/
  - /^bugfix.*$/

.gometalinter-template: &gometalinter-template
  <<: *dev-only
  image: scalify/glide:0.13.0
  stage: lint
  dependencies:
  - Get Dependencies
  variables:
    OPTIONS: --deadline=5m --vendor --disable-all --skip=proto --sort=severity
  script:
    - go get github.com/alecthomas/gometalinter
    - gometalinter -i
    - gometalinter $OPTIONS --enable=$CI_JOB_NAME ./...

before_script:
  - mkdir -p $GOPATH/src/gitlab.com/$CI_PROJECT_NAMESPACE
  - echo "Running in $GOPATH/src/gitlab.com/$CI_PROJECT_PATH"
  - ln -s $CI_PROJECT_DIR/ $GOPATH/src/gitlab.com/$CI_PROJECT_PATH
  - cd $GOPATH/src/gitlab.com/$CI_PROJECT_PATH
  - pwd
  - mkdir -p ~/.kube

variables:
  CGO_ENABLED: 0

stages:
  - dependencies
  - lint
  - test
  - build

Get Dependencies:
  <<: *dev-only
  image: scalify/glide:0.13.0
  stage: dependencies
  artifacts:
    paths:
    - vendor/
    expire_in: 1 day
    untracked: true
  script:
    - glide install --strip-vendor

deadcode:
  <<: *gometalinter-template
errcheck:
  <<: *gometalinter-template
vet:
  <<: *gometalinter-template
goconst:
  <<: *gometalinter-template
gocyclo:
  <<: *gometalinter-template
  allow_failure: true
golint:
  <<: *gometalinter-template
  allow_failure: true
ineffassign:
  <<: *gometalinter-template
  allow_failure: true
misspell:
  <<: *gometalinter-template
  allow_failure: true
unparam:
  <<: *gometalinter-template
  allow_failure: true
dupl:
  <<: *gometalinter-template
  allow_failure: true
staticcheck:
  <<: *gometalinter-template
  allow_failure: true
gas:
  <<: *gometalinter-template
  allow_failure: true
lll:
  <<: *gometalinter-template
  allow_failure: true
goimports:
  <<: *gometalinter-template
  allow_failure: true
unconvert:
  <<: *gometalinter-template
  allow_failure: true
vetshadow:
  <<: *gometalinter-template
  allow_failure: true
interfacer:
  <<: *gometalinter-template
  allow_failure: true
gosimple:
  <<: *gometalinter-template
  allow_failure: true
gotype:
  <<: *gometalinter-template
  allow_failure: true
unused:
  <<: *gometalinter-template
  allow_failure: true
nakedret:
  <<: *gometalinter-template
  allow_failure: true

Test:
  image: scalify/glide:0.13.0
  stage: test
  dependencies:
  - Get Dependencies
  script:
  - go test ./...
  allow_failure: true
  <<: *dev-only

Build Application:
  image: scalify/glide:0.13.0
  stage: test
  dependencies:
  - Get Dependencies
  artifacts:
    paths:
    - $CI_PROJECT_NAME
  script:
  - GOOS=linux go build -v -ldflags '-w -extldflags '-static'' .
  <<: *dev-only

build-docker-image-master:
  <<: *docker
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build-docker-image-tags:
  <<: *docker
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - tags
