version: "3"
services:
  gateway:
    build: .
    networks:
      - puppet_master
    environment:
      - "COUCH_DB_HOST=database"
      - "COUCH_DB_PORT=6984"
      - "COUCH_DB_USERNAME=puppet"
      - "COUCH_DB_PASSWORD=puppet"
      - "QUEUE_HOST=queue"
      - "QUEUE_PORT=5672"
      - "QUEUE_USERNAME=puppet"
      - "QUEUE_PASSWORD=puppet"
    command: "server"
    links:
      - database
      - queue
  database:
    image: couchdb:2.1.1
    volumes:
      - "./data/couchdb:/opt/couchdb/data"
    networks:
      - puppet_master
    environment:
      - "COUCHDB_USER=puppet"
      - "COUCHDB_PASSWORD=puppet"
    ports:
      - "5984:5984"
  queue:
    image: rabbitmq:3.7.4-management-alpine
    environment:
      - "RABBITMQ_DEFAULT_USER=puppet"
      - "RABBITMQ_DEFAULT_PASS=puppet"
    volumes:
      - "./data/queue:/var/lib/rabbitmq"
    expose:
      - "5672"
    networks:
      - puppet_master
    ports:
      - "15672:15672"

networks:
  default: {}
  puppet_master: {}
